SELECT A.PRODUCT_ID, A.PRODUCT_NAME, (A.PRICE * B.AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT as A INNER JOIN
(
    SELECT PRODUCT_ID, SUM(AMOUNT) as AMOUNT
    FROM FOOD_ORDER
    WHERE MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
) as B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC;