-- 코드를 입력하세요
SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM APPOINTMENT as A 
    INNER JOIN PATIENT as B
        ON A.PT_NO = B.PT_NO 
    INNER JOIN DOCTOR as C
        ON A.MDDR_ID = C.DR_ID
WHERE DATE(A.APNT_YMD) = "2022-04-13" 
AND A.MCDP_CD = "CS" 
AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD;

